### ISSUE TITLE
Mouse cursor is incorrectly offset after using borderless gaming

### ISSUE THREAD

**Issue by Question2** [Codeusa/Borderless-Gaming#73] opened 2014-09-03 12:12 UTC
I tried using the program with a game called Civilizations V, and while the mod works, it makes the mouse cursor offset so the actual pointer area is not the same as the mouse cursor on the screen. Any chance you guys can fix this?

**Comment by Codeusa** [comment] 2015-01-08 04:09
Fixed in 7.5

**Closed by Codeusa** 2015-01-08 04:09 UTC

**Comment by JamiePoole** [comment] 2015-02-01 14:40
Hello, this hasn't been fixed for me in LOTRO. Using 7.9

**Comment by psouza4** [comment] 2015-02-01 18:00
I don't know how this was "fixed" in 7.5.  Andrew may need to chime in because I think he was thinking of a different issue.

This is likely not something that can be fixed, as many games are just programmed to understand the window working resolution they set and not the resolution that was adjusted.

**Comment by madpew** [comment] 2015-02-05 09:27
@JamiePoole Kinda offtopic, but yesterdays patch added a native borderless-mode to the LOTRO-client.

**Comment by JamiePoole** [comment] 2015-02-06 09:20
@madpew Great :) Problem irrelevant then. Disregard me lol :)

**Comment by Raepheles** [comment] 2019-03-13 16:56
@Codeusa Either it's not fixed or problem resurfaced again since I have this problem on 9.5.5 which is the latest version as of now.

**Comment by Evernow** [comment] 2019-12-01 03:16
@Codeusa I can confirm what others have said, this issue resurfaced again

**Comment by Syllvae** [comment] 2019-12-19 23:17
Using version 9.5.6 and can confirm the issue is still present in my The Witcher EE game. Interesting enough, mouse pointer is off only in menus (inventory, journal, main menu, etc), in game, ie 3D environment, mouse pointer works perfectly.

**Comment by charlesnelson9** [comment] 2020-01-20 20:12
@Syllvae I had the same problem in Witcher EE, but I fixed it by clicking "Tools > Toggle Windows Taskbar Visibility". My taskbar wasn't visible to begin with (at least not in game), but clicking that option caused the window to "shift up" (like more of the bottom became visible without losing any visibility at the top). Then my cursor was properly aligned in both menus and 3D environment. This is on windows 10 with BG 9.5.6

**Comment by RedSnt** [comment] 2023-12-20 21:38
Problem is probably mostly with Civilization 5 in this case, not sure how this can be fixed. Never the less, still an annoyance in late 2023. Doesn't matter if one use hide menus or hide windows bar, the game seems to do one calibration and that's it - cursor offset.
