### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by Razunter** [Codeusa/Borderless-Gaming#51] opened 2014-04-03 13:37 UTC
Borderless Gaming v6.0 uses 4-5% CPU every second when inactive on my i7-3770K. It's too much.

**Comment by Waester** [comment] 2015-02-10 18:32
High CPU usage returned on version 7+, version 6.5 is still ok.
(Not high cpu, more like constant cpu on 5%+)

**Comment by psouza4** [comment] 2015-02-10 18:42
I would find out if there's an unresponsive app running on your computer.  New methods of enumerating window properties were added to Borderless Gaming 7.5+ that could cause an increase in CPU usage a window was misbehaving or unresponsive.  You can troubleshoot by closing various programs to see if CPU usage reduces.

**Comment by SnowGabe** [comment] 2015-07-14 11:49
For me the CPU usage is around 20%. This is too much.

**Comment by psouza4** [comment] 2015-07-14 14:40
Then you likely have a misbehaving app that isn't responding to the Win32
APIs for reading process windows and titles.

I would investigate by trying to locate the misbehaving application.

On Tue, Jul 14, 2015 at 5:50 AM, SnowGabe <notifications@github.com> wrote:

> For me the CPU usage is around 20%. This is too much.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Codeusa/Borderless-Gaming/issues/51#issuecomment-121213679>
> .
>



-- 
-Pete

**Comment by SnowGabe** [comment] 2015-07-14 18:06
@psouza4 Do you have any suggestions how to find that application? Any log that I could attach?

**Comment by Southpaw018** [comment] 2015-07-24 19:16
Just installed and can confirm that BG is averaging 25.1% processor time and 3.9% user time at all times with Automatic Processing enabled, and 24.6% processor time and 3.4% user time with Automatic Processing disabled. These are running 90 sec averages from perfmon.

Upon disabling Automatic Processing, overall CPU use does drop to ~0% after a few seconds and then remains there for a few more seconds, but then resumes the average values listed. The short 0% period is **not* factored in to the averages above.

This tells me that the high idle CPU usage is not, as stated earlier in this thread, due to misbehaving applications. Nor is it negligible. This issue should not be closed.

![bg cpu usage](https://cloud.githubusercontent.com/assets/806128/8882692/f82ac524-3216-11e5-942d-f8dc1307a932.png)

**Comment by psouza4** [comment] 2015-07-24 19:21
Nobody's closed this issue and myself and other developers are actively discussing methods to work around the problem.  Almost all of the CPU usage is from Windows hanging when we ask it to use a native API to request the window caption for all the running applications -- if any of the running applications on your computer are sleeping on the main UI thread (a giant no-no, but happens a lot with lazy or poor programming), Windows will hang for a long time before aborting back to our application.  During this time, Windows will report that our application is using a lot of CPU while waiting for Windows to respond with caption text.  This is also why the problem does not occur on versions prior to 7.x, when we only tracked the process binary name and not caption text.

When we have a solid workaround for polling caption information from misbehaving applications, we'll let you know and we'll update this issue accordingly.

**Comment by Southpaw018** [comment] 2015-07-24 23:11
Thanks, @psouza4. Some of the comments upthread made it sound like you (collective you) thought it wasn't your issue, or it wasn't important. Good to hear that you're working on it. I'll pony up for the Steam version tonight, and watch for updates and a fix for this. It's the only thing keeping me from switching from my ancient, barely-works-any-more borderless proggy. :)

**Comment by psouza4** [comment] 2015-07-26 19:40
I encourage you to update to Borderless Gaming 8.2:

https://github.com/Codeusa/Borderless-Gaming/releases/tag/8.2

Several optimizations have been made to reduce CPU use and improve performance and responsiveness.

**Comment by karasuhebi** [comment] 2015-07-27 22:48
I was having issues with CPU utilization as well. I can confirm that BG is behaving A LOT better in v8.2. Cheers!

**Comment by psouza4** [comment] 2015-07-27 22:52
Thanks for the update!

**Closed by psouza4** 2015-07-27 22:52 UTC

**Comment by Southpaw018** [comment] 2015-08-18 13:20
I'm late to the party, but I can also confirm that BG's CPU usage is greatly improved. I "donated" via Steam purchase a while ago in thanks. Keep up the good work, guys!

**Comment by LavenderMoon** [comment] 2015-08-18 17:25
There's a Steam version? Nice, I'll probably pick it up when I get paid.
