### ISSUE TITLE
Problems with Killing Floor and Possibly Title-less Windows

### ISSUE THREAD

**Issue by Synopis** [Codeusa/Borderless-Gaming#93] opened 2015-01-09 00:39 UTC
I had just updated to 7.5 and found out that the app won't make Killing Floor (KF) borderless anymore. I assumed that this is due to it going by the window title (KF doesn't have one). I had tried to manually add it via favorites and set a custom window title to no avail. I am not sure if the app has problems with windows with no names.

**Comment by psouza4** [comment] 2015-01-09 01:24
Right-click on the game from the list of applications and choose to add to favorites -> by process name.

This will resolve your issue.

**Comment by Synopis** [comment] 2015-01-09 02:11
Unfortunately that doesn't work. I had also tried Euro Truck Simulator 2 and it also doesn't work by process name or window title.

**Comment by Codeusa** [comment] 2015-01-09 05:27
Hi Synopis, I've noticing this behavior with KF as well, it seems to be related to the process containing no window information. 

to bypass selected from the options menu of 7.5 "View Full Process Details" and try manually setting it to fullscreen

- Andrew

**Comment by Synopis** [comment] 2015-01-09 15:10
That works once as you need to (at least from what I observed) restart the app every time you launch KF. Taking a look at the process details... it's KillingFloor [#xxxx] [00000000.00000000] after every exit of KF while leaving the app open. After every re-open of KF and Borderless Gaming... it's KillingFloor [#xxxx] [14cf0000.00040100].

**Comment by Codeusa** [comment] 2015-01-09 16:03
I will push a fix for this shortly.

**Comment by psouza4** [comment] 2015-01-09 16:08
I'm installing Killing Floor to investigate this issue as it sounds suspiciously like use error.  I'm not sure there's anything to fix here, yet.

**Comment by Chocodemon** [comment] 2015-01-09 16:54
Soo, i have a problem that sounds just like this with MGS:Ground Zeroes and the problem seems to be with the "favorites" list. When I have the game in the list, nothing happens and even the "make borderless" button doesn't work, but if I take the game out of the list and then put it back on, it works like a charm.... until you open the game anew, or change the window mode.

I made a video to visualize this. 
https://www.youtube.com/watch?v=THLXkQPCu1s

**Comment by psouza4** [comment] 2015-01-09 17:40
Confirmed that this was a fixable issue due to odd behavior in some games that switch window handles or styles post-launch.  Fixed in version 7.6

**Comment by Synopis** [comment] 2015-01-09 19:01
7.6 ticks the option for full screen instead of leaving it in a window. Un ticking full screen makes the game play in a window but the app won't make it into a borderless window without it changing to full screen. I still have to restart the app to get it to recognize the game.

**Comment by psouza4** [comment] 2015-01-09 19:04
Add the game to your favorites as usual (it will display [Max] next to it in your favorites list).  Launch the game.  During the course of the game launching, the Unity engine will switch the main window's styles a few times, to which Borderless Gaming 6.5 or 7.6 will persistently switch back to borderless.  After a few moments using either version, the game will be borderless and you can tab in and out of it.

I own this game ("The Killing Floor") and personally tested and confirmed that it now works correctly in Borderless Gaming version 7.6.

Additionally, you don't have to restart the app, ever, to get it to recognize window changes.. if, for some reason, it's not working automatically, you can always use the new Tools menu to forcibly refresh the application list.

**Comment by psouza4** [comment] 2015-01-11 02:28
Synopsis: The Killing Floor itself is switching to full screen when the window borders are removed **and** the window is maximized.  Simply tell Borderless Gaming to not maximize that window (a right-click option from your Favorites list).  My preferred settings for The Killing Floor are: (1) Full Screen and (2) Adjust Window Bounds (0L, 1R, 0T, 3B).

Synopsis: Euro Truck Simulator 2 works fine with Borderless Gaming version 7.6.  I couldn't find any issues.

Chocodemon: Metal Gear Solid: Ground Zeroes works fine with Borderless Gaming version 7.6.  Bear in mind that in your video, you are clicking buttons without first selecting the application, so nothing is supposed to happen.  Version 7.7 will make it obvious by disabling those buttons if there isn't an active selection.  Additionally, MGS:GZ has a built-in borderless window mode you can use natively without Borderless Gaming's help.

**Closed** 2015-07-28 14:51 UTC

**Comment by Dol-phin** [comment] 2015-08-01 08:08
@psouza4 I'm using your settings and the game doesn't go to fullscreen. The menus are also partially white.

**Comment by reddit-is-fun** [comment] 2016-07-25 11:01
I've found that using AutoHotkey works far better for Killing Floor than BG. I use this script (`Alt + F` hotkey) and I can switch between borderless fullscreen and windowed efficiently, graphics bugs no longer appear:

```
#NoEnv  ; Recommended for performance and compatibility with future AutoHotkey releases.
; #Warn  ; Enable warnings to assist with detecting common errors.
SendMode Input  ; Recommended for new scripts due to its superior speed and reliability.
SetWorkingDir %A_ScriptDir%  ; Ensures a consistent starting directory.

#UseHook On
!f::
WinGet, TempWindowID, ID, A
If (WindowID != TempWindowID)
{
  WindowID:=TempWindowID
  WindowState:=0
}
If (WindowState != 1)
{
  WinGetPos, WinPosX, WinPosY, WindowWidth, WindowHeight, ahk_id %WindowID%
  WinSet, Style, -0xC40000, ahk_id %WindowID%
  WinMove, ahk_id %WindowID%, , 0, 0, A_ScreenWidth, A_ScreenHeight
  ;Hide Windows Task Bar and Start Button. (Remove the following two lines if you don't want that behaviour)
  WinHide ahk_class Shell_TrayWnd
  WinHide Start ahk_class Button
}
Else
{
  WinSet, Style, +0xC40000, ahk_id %WindowID%
  WinMove, ahk_id %WindowID%, , WinPosX, WinPosY, WindowWidth, WindowHeight
  ;Show the task bar again
  WinShow ahk_class Shell_TrayWnd
  WinShow Start ahk_class Button
}
WindowState:=!WindowState
return
```

**Comment by 07416** [comment] 2017-06-22 18:49
Support for games without titles was added in version [9.0](https://github.com/Codeusa/Borderless-Gaming/releases/tag/9.0). Killing Floor still doesn't work, I'm using version 9.3:

![screenshot 25](https://user-images.githubusercontent.com/14923168/27450527-a43f0916-5794-11e7-8e37-f4459bf0121b.png)

![screenshot 26](https://user-images.githubusercontent.com/14923168/27450508-9b092b38-5794-11e7-8271-a4aa055aedb8.png)

As you can see, the window is off.

**Comment by Codeusa** [comment] 2017-06-22 18:55
Actually it does work, you just need to manually set your window resolution after it goes Borderless.
