### ISSUE TITLE
Automatically lock mouse option

### ISSUE THREAD

**Issue by sneaky4oe** [Codeusa/Borderless-Gaming#202] opened 2015-10-24 13:07 UTC
An option for favorites to automatically lock mouse in them while they're in focus would be really usefull.Can't fix it all the time for CSGO and spect Dota.

**Comment by Driphter** [comment] 2015-10-24 13:56
Intuitively, hiding the cursor should work similarly. :)

**Comment by sneaky4oe** [comment] 2015-10-24 14:00
But will it hide cursor in strageties or moba? Or in main menu of shooters?..

**Comment by Driphter** [comment] 2015-10-24 19:31
I meant it would be nice if you were able to have the cursor hidden automatically in certain games. Same as you suggested for locking cursors. Its a feature currently supported that is useful for games in which the cursor should probably be hidden but isn't.

**Comment by psouza4** [comment] 2015-11-25 18:02
Duplicate of issue #137

**Closed by psouza4** 2015-11-25 18:02 UTC
Labels: duplicate
