### ISSUE TITLE
Windows 10 ThreadException

### ISSUE THREAD

**Issue by Sponge97** [Codeusa/Borderless-Gaming#191] opened 2015-08-22 03:08 UTC
Everytime I run Borderless-Gaming I get an error. No windows can be used by the application, rendering it useless. I also get the same error log everytime.

The error file can be found here: http://pastebin.com/5MMrL0y2

**Comment by YabbaTroll** [comment] 2015-09-21 22:20
I'm having the same problem here on windows 10
All my info is right here https://steamcommunity.com/app/388080/discussions/1/535152511352343566/

**Comment by psouza4** [comment] 2015-11-25 17:55
This is caused by a corrupt favorites file.  Will roll out a fix before long.

**Comment by psouza4** [comment] 2015-11-25 18:53
Resolved in version 8.3.

**Closed by psouza4** 2015-11-25 18:53 UTC
Labels: fixed bug

**Comment by Acecool** [comment] 2016-01-12 08:42
The exception resolves nothing because favorites still don't load even if all folders exist ( and registry too ).

https://github.com/Codeusa/Borderless-Gaming/issues/225
