### ISSUE TITLE
Mod Organizer 2 will not revert to bordered state

### ISSUE THREAD

**Issue by hardslaps** [Codeusa/Borderless-Gaming#589] opened 2023-01-22 13:53 UTC
Accidentally favorited my MO2 window and now I cant reverse the process. Please help

**Comment by KingBophades** [comment] 2023-02-27 21:38
Duplicate of #553, but honestly, if it gets more attention this way, the better.

**Comment by KingBophades** [comment] 2023-02-27 22:29
### Alright, posting it here because it's the most recent post, but I fixed it.

Just to be sure it's been removed by **Borderless-Gaming**, make sure to remove MO2 from **favorites** & attempt to revert to bordered using the **bottom button in the center of the application**. After that close **both** MO2 & Borderless-Gaming (Make sure it's gone from the **system tray too**). 

From here, you need to navigate to where-ever your ModOrganizer2 **install folder** is (Appdata/Local/Program Files) & open the `ModOrganizer.ini` file with notepad or some other text editor.

Make your way all the way down until you find the `[Geometry]` section. There, delete all the values underneath it and save.
 
 Once you start Mo2 again, it should be fixed.

Cheers! 🍻

**Closed** 2024-02-20 20:41 UTC

**Comment by newyearnewboof** [comment] 2025-04-19 02:39
> ### Alright, posting it here because it's the most recent post, but I fixed it.
> Just to be sure it's been removed by **Borderless-Gaming**, make sure to remove MO2 from **favorites** & attempt to revert to bordered using the **bottom button in the center of the application**. After that close **both** MO2 & Borderless-Gaming (Make sure it's gone from the **system tray too**).
> 
> From here, you need to navigate to where-ever your ModOrganizer2 **install folder** is (Appdata/Local/Program Files) & open the `ModOrganizer.ini` file with notepad or some other text editor.
> 
> Make your way all the way down until you find the `[Geometry]` section. There, delete all the values underneath it and save.
> 
> Once you start Mo2 again, it should be fixed.
> 
> Cheers! 🍻

after all this time it still works. thank you.

wish i knew why this was marked as completed, doesn't make any sense to me.
