### ISSUE TITLE
Change Hotkeys

### ISSUE THREAD

**Issue by Zhior** [Codeusa/Borderless-Gaming#207] opened 2015-11-16 07:41 UTC
I'm using the Mouse Lock Hotkey but unfortunately my Scroll Lock key turns on/off the backlight on my keyboard (no way to change that afaik) so using Scroll Lock as a hotkey is understandably impossible. It'd be cool if we could change the hotkey to whatever we wanted to. 

EDIT: I changed the source code myself and recompiled it to change it to a different key (I used the Home key); it'd still be cool if an option was added to change it though. There's a small issue though: my Home key no longer works while the program is open, BG seems to have taken complete control of it and I can't use it to navigate webpages or text. I suggest that the hotkey only apply to programs that are in the favorite list.

**Comment by McCovican** [comment] 2015-11-18 20:27
Agreed, I came here to open a topic about this. I'm looking to be able to change the Global hotkey, even if it's just via a config file. I'm unfortunately not quite sure how I'd go about compiling this myself on windows.

As an example, I'm currently trying it with Wolfenstein: The New Order. If I alt-tab out of the game to get at something, then return, the game automatically returns to a normal windowed mode upon becoming active. It then blocks the windows key, preventing me from re-applying the borderless window (thus somewhat defying the purpose of the program to me).

**Comment by psouza4** [comment] 2015-11-25 18:00
Duplicate of issue #136

**Closed by psouza4** 2015-11-25 18:00 UTC
Labels: duplicate
