### ISSUE TITLE
Request: Option to Prevent Screensaver with a Specified Favorite

### ISSUE THREAD

**Issue by TathagataDM** [Codeusa/Borderless-Gaming#192] opened 2015-08-24 08:20 UTC
I was just hoping it's possible to add an option to suppress the screensaver while a given favorite is open. Similar to the options for favorite items such as hiding the mouse cursor or taskbar. Often during cutscenes the screensaver comes up, and currently the only options seem to be to disable the screensaver or increase the timeout, neither of which are good solutions since they need to be reverted once the game is closed. 

Thanks for reading, my apologies if this is an inappropriate way to ask this.

**Comment by SwinglesMan** [comment] 2015-08-25 03:10
https://github.com/Codeusa/Borderless-Gaming/issues/163

**Comment by psouza4** [comment] 2015-11-25 18:08
As @SwinglesMan pointed out, this is essentially a duplicate of request issue #163

**Closed by psouza4** 2015-11-25 18:08 UTC
Labels: duplicate
